export interface CollegeData {
  name: string
  state: string
  fees: number
  courses: string[]
  naacGrade: string
  website?: string
}

export const states = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry'
]

export const courses = [
  'B.Tech Computer Science', 'B.Tech Electronics', 'B.Tech Mechanical', 'B.Tech Civil', 'B.Tech Chemical', 'B.Tech Electrical', 'B.Tech Information Technology', 'B.Tech Biotechnology', 'B.Tech Aerospace', 'B.Tech Mining',
  'B.Sc Physics', 'B.Sc Chemistry', 'B.Sc Mathematics', 'B.Sc Biology', 'B.Sc Computer Science', 'B.Sc Electronics', 'B.Sc Statistics', 'B.Sc Environmental Science', 'B.Sc Agriculture', 'B.Sc Psychology',
  'B.Com', 'B.Com (Hons)', 'BBA', 'BBA (Hons)', 'BBA Finance', 'BBA Marketing', 'BBA Human Resources', 'BBA International Business', 'BBA Digital Marketing', 'BBA Entrepreneurship',
  'BA English', 'BA History', 'BA Political Science', 'BA Economics', 'BA Sociology', 'BA Psychology', 'BA Geography', 'BA Philosophy', 'BA Journalism', 'BA Mass Communication',
  'BCA', 'B.Sc IT', 'B.Sc Data Science', 'B.Sc Artificial Intelligence', 'B.Sc Cyber Security', 'B.Sc Cloud Computing', 'B.Sc Mobile App Development', 'B.Sc Web Development', 'B.Sc Game Development', 'B.Sc Digital Marketing',
  'Diploma Computer Science', 'Diploma Electronics', 'Diploma Mechanical', 'Diploma Civil', 'Diploma Electrical', 'Diploma Chemical', 'Diploma Information Technology', 'Diploma Biotechnology', 'Diploma Mining', 'Diploma Textile',
  'MBBS', 'BDS', 'B.Pharm', 'B.Sc Nursing', 'BPT', 'BOT', 'B.Sc Medical Technology', 'B.Sc Radiography', 'B.Sc Optometry', 'B.Sc Physiotherapy',
  'B.Arch', 'B.Plan', 'B.Des', 'BFA', 'BVA', 'B.Music', 'B.Dance', 'B.Drama', 'B.Fashion Design', 'B.Interior Design',
  'B.Ed', 'B.P.Ed', 'B.Lib.I.Sc', 'B.LIS', 'B.Social Work', 'B.Tourism', 'B.Hotel Management', 'B.Culinary Arts', 'B.Event Management', 'B.Animation'
]

export const colleges: CollegeData[] = [
  { name: 'Indian Institute of Technology Madras', state: 'Tamil Nadu', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Mechanical','B.Tech Chemical'], naacGrade: 'A++', website: 'https://www.iitm.ac.in' },
  { name: 'Indian Institute of Technology Delhi', state: 'Delhi', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++', website: 'https://www.iitd.ac.in' },
  { name: 'Indian Institute of Technology Bombay', state: 'Maharashtra', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++', website: 'https://www.iitb.ac.in' },
  { name: 'Indian Institute of Technology Kanpur', state: 'Uttar Pradesh', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Aerospace'], naacGrade: 'A++', website: 'https://www.iitk.ac.in' },
  { name: 'Indian Institute of Technology Kharagpur', state: 'West Bengal', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Mining','B.Tech Civil'], naacGrade: 'A++', website: 'https://www.iitkgp.ac.in' },
  { name: 'Indian Institute of Science Bangalore', state: 'Karnataka', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisc.ac.in' },
  { name: 'Jadavpur University', state: 'West Bengal', fees: 15000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++', website: 'https://www.jaduniv.edu.in' },
  { name: 'Anna University', state: 'Tamil Nadu', fees: 50000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++', website: 'https://www.annauniv.edu' },
  { name: 'University of Delhi', state: 'Delhi', fees: 20000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Com','BA English'], naacGrade: 'A++', website: 'https://www.du.ac.in' },
  { name: 'Jamia Millia Islamia', state: 'Delhi', fees: 15000, courses: ['B.Tech Computer Science','B.Sc Physics','B.Com','BA History'], naacGrade: 'A++', website: 'https://www.jmi.ac.in' },
  { name: 'Banaras Hindu University', state: 'Uttar Pradesh', fees: 25000, courses: ['B.Tech Computer Science','B.Sc Physics','B.Sc Chemistry','BA English'], naacGrade: 'A++', website: 'https://www.bhu.ac.in' },
  { name: 'Aligarh Muslim University', state: 'Uttar Pradesh', fees: 20000, courses: ['B.Tech Computer Science','B.Sc Physics','B.Com','BA History'], naacGrade: 'A++', website: 'https://www.amu.ac.in' },
  { name: 'University of Hyderabad', state: 'Telangana', fees: 30000, courses: ['B.Tech Computer Science','B.Sc Physics','B.Sc Chemistry','BA English'], naacGrade: 'A++' },
  { name: 'Jawaharlal Nehru University', state: 'Delhi', fees: 20000, courses: ['B.Sc Physics','B.Sc Chemistry','BA English','BA History'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Roorkee', state: 'Uttarakhand', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Civil','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Guwahati', state: 'Assam', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Indore', state: 'Madhya Pradesh', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Bhubaneswar', state: 'Odisha', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Gandhinagar', state: 'Gujarat', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Chemical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Ropar', state: 'Punjab', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Mandi', state: 'Himachal Pradesh', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Patna', state: 'Bihar', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Jodhpur', state: 'Rajasthan', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Goa', state: 'Goa', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Bhilai', state: 'Chhattisgarh', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Dharwad', state: 'Karnataka', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Tirupati', state: 'Andhra Pradesh', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Palakkad', state: 'Kerala', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Jammu', state: 'Jammu and Kashmir', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A++' },
  { name: 'Indian Institute of Technology Dhanbad', state: 'Jharkhand', fees: 250000, courses: ['B.Tech Computer Science','B.Tech Mining','B.Tech Mechanical'], naacGrade: 'A++' },
  { name: 'National Institute of Technology Trichy', state: 'Tamil Nadu', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Warangal', state: 'Telangana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Surathkal', state: 'Karnataka', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Calicut', state: 'Kerala', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Rourkela', state: 'Odisha', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Durgapur', state: 'West Bengal', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Allahabad', state: 'Uttar Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Kurukshetra', state: 'Haryana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Jaipur', state: 'Rajasthan', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Hamirpur', state: 'Himachal Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Jalandhar', state: 'Punjab', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Srinagar', state: 'Jammu and Kashmir', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Patna', state: 'Bihar', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Goa', state: 'Goa', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Manipur', state: 'Manipur', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Meghalaya', state: 'Meghalaya', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Mizoram', state: 'Mizoram', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Nagaland', state: 'Nagaland', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Arunachal Pradesh', state: 'Arunachal Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Sikkim', state: 'Sikkim', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Tripura', state: 'Tripura', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Puducherry', state: 'Puducherry', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Delhi', state: 'Delhi', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Uttarakhand', state: 'Uttarakhand', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Karnataka', state: 'Karnataka', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Andhra Pradesh', state: 'Andhra Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Telangana', state: 'Telangana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Kerala', state: 'Kerala', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Tamil Nadu', state: 'Tamil Nadu', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Maharashtra', state: 'Maharashtra', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Gujarat', state: 'Gujarat', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Madhya Pradesh', state: 'Madhya Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Rajasthan', state: 'Rajasthan', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Uttar Pradesh', state: 'Uttar Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology West Bengal', state: 'West Bengal', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Odisha', state: 'Odisha', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Jharkhand', state: 'Jharkhand', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Chhattisgarh', state: 'Chhattisgarh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Bihar', state: 'Bihar', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Assam', state: 'Assam', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Himachal Pradesh', state: 'Himachal Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Punjab', state: 'Punjab', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Haryana', state: 'Haryana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Delhi', state: 'Delhi', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Uttarakhand', state: 'Uttarakhand', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Karnataka', state: 'Karnataka', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Andhra Pradesh', state: 'Andhra Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Telangana', state: 'Telangana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Kerala', state: 'Kerala', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Tamil Nadu', state: 'Tamil Nadu', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Maharashtra', state: 'Maharashtra', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Gujarat', state: 'Gujarat', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Madhya Pradesh', state: 'Madhya Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Rajasthan', state: 'Rajasthan', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Uttar Pradesh', state: 'Uttar Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology West Bengal', state: 'West Bengal', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Odisha', state: 'Odisha', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Jharkhand', state: 'Jharkhand', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Chhattisgarh', state: 'Chhattisgarh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Bihar', state: 'Bihar', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Assam', state: 'Assam', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Himachal Pradesh', state: 'Himachal Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Punjab', state: 'Punjab', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Haryana', state: 'Haryana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Delhi', state: 'Delhi', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Uttarakhand', state: 'Uttarakhand', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Karnataka', state: 'Karnataka', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Andhra Pradesh', state: 'Andhra Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Telangana', state: 'Telangana', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A+' },
  { name: 'National Institute of Technology Kerala', state: 'Kerala', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A+' },
  
  // ANDHRA PRADESH - Local & Private Colleges
  { name: 'Acharya Nagarjuna University', state: 'Andhra Pradesh', fees: 25000, courses: ['B.Tech Computer Science','B.Sc Physics','B.Com','BA English'], naacGrade: 'A' },
  { name: 'Andhra University', state: 'Andhra Pradesh', fees: 30000, courses: ['B.Tech Computer Science','B.Sc Chemistry','B.Com','BA History'], naacGrade: 'A' },
  { name: 'Sri Venkateswara University', state: 'Andhra Pradesh', fees: 20000, courses: ['B.Tech Electronics','B.Sc Mathematics','BBA','BA Political Science'], naacGrade: 'A' },
  { name: 'Koneru Lakshmaiah Education Foundation', state: 'Andhra Pradesh', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Mechanical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'VIT University Vellore', state: 'Andhra Pradesh', fees: 200000, courses: ['B.Tech Computer Science','B.Tech Electronics','BBA','B.Sc Physics'], naacGrade: 'A' },
  { name: 'SRM University AP', state: 'Andhra Pradesh', fees: 180000, courses: ['B.Tech Computer Science','B.Tech Civil','BBA','B.Sc Chemistry'], naacGrade: 'A' },
  { name: 'GITAM University', state: 'Andhra Pradesh', fees: 120000, courses: ['B.Tech Computer Science','B.Tech Mechanical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'JNTU Kakinada', state: 'Andhra Pradesh', fees: 40000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A' },
  { name: 'JNTU Anantapur', state: 'Andhra Pradesh', fees: 35000, courses: ['B.Tech Computer Science','B.Tech Mechanical','B.Tech Chemical'], naacGrade: 'A' },
  { name: 'Rayalaseema University', state: 'Andhra Pradesh', fees: 15000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Com','BA English'], naacGrade: 'A' },
  { name: 'Krishna University', state: 'Andhra Pradesh', fees: 20000, courses: ['B.Sc Mathematics','B.Com','BA History','BBA'], naacGrade: 'A' },
  { name: 'Yogi Vemana University', state: 'Andhra Pradesh', fees: 18000, courses: ['B.Sc Biology','B.Com','BA Political Science','BBA'], naacGrade: 'A' },
  { name: 'Dravidian University', state: 'Andhra Pradesh', fees: 12000, courses: ['BA English','BA History','B.Com','B.Sc Physics'], naacGrade: 'A' },
  { name: 'Adikavi Nannaya University', state: 'Andhra Pradesh', fees: 15000, courses: ['BA English','B.Com','B.Sc Chemistry','BBA'], naacGrade: 'A' },
  { name: 'Dr. B.R. Ambedkar University', state: 'Andhra Pradesh', fees: 10000, courses: ['BA History','B.Com','B.Sc Mathematics','BA Political Science'], naacGrade: 'A' },
  
  // ARUNACHAL PRADESH - Local & Private Colleges
  { name: 'Rajiv Gandhi University', state: 'Arunachal Pradesh', fees: 15000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'North Eastern Regional Institute of Science and Technology', state: 'Arunachal Pradesh', fees: 50000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A' },
  { name: 'Indira Gandhi Government College', state: 'Arunachal Pradesh', fees: 8000, courses: ['BA English','B.Com','B.Sc Physics','BA Political Science'], naacGrade: 'A' },
  { name: 'Donyi Polo Government College', state: 'Arunachal Pradesh', fees: 10000, courses: ['BA History','B.Com','B.Sc Chemistry','BA English'], naacGrade: 'A' },
  { name: 'Jawaharlal Nehru College', state: 'Arunachal Pradesh', fees: 12000, courses: ['B.Sc Mathematics','B.Com','BA English','BBA'], naacGrade: 'A' },
  
  // ASSAM - Local & Private Colleges
  { name: 'Gauhati University', state: 'Assam', fees: 20000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'Dibrugarh University', state: 'Assam', fees: 18000, courses: ['B.Tech Computer Science','B.Sc Chemistry','B.Com','BA Political Science'], naacGrade: 'A' },
  { name: 'Tezpur University', state: 'Assam', fees: 25000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Sc Physics','BBA'], naacGrade: 'A' },
  { name: 'Kaziranga University', state: 'Assam', fees: 80000, courses: ['B.Tech Computer Science','B.Tech Mechanical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Assam Don Bosco University', state: 'Assam', fees: 100000, courses: ['B.Tech Computer Science','BBA','B.Com','B.Sc Physics'], naacGrade: 'A' },
  { name: 'Krishna Kanta Handique State Open University', state: 'Assam', fees: 15000, courses: ['BA English','B.Com','B.Sc Mathematics','BA History'], naacGrade: 'A' },
  { name: 'Bodoland University', state: 'Assam', fees: 12000, courses: ['BA English','B.Com','B.Sc Physics','BA Political Science'], naacGrade: 'A' },
  { name: 'Cotton University', state: 'Assam', fees: 15000, courses: ['B.Sc Chemistry','B.Com','BA English','B.Sc Mathematics'], naacGrade: 'A' },
  { name: 'Darrang College', state: 'Assam', fees: 8000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'B. Borooah College', state: 'Assam', fees: 10000, courses: ['B.Sc Chemistry','B.Com','BA English','B.Sc Mathematics'], naacGrade: 'A' },
  
  // BIHAR - Local & Private Colleges
  { name: 'Patna University', state: 'Bihar', fees: 15000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'Magadh University', state: 'Bihar', fees: 12000, courses: ['B.Sc Chemistry','B.Com','BA English','B.Sc Mathematics'], naacGrade: 'A' },
  { name: 'Bhagalpur University', state: 'Bihar', fees: 10000, courses: ['BA History','B.Com','B.Sc Physics','BA Political Science'], naacGrade: 'A' },
  { name: 'Veer Kunwar Singh University', state: 'Bihar', fees: 8000, courses: ['BA English','B.Com','B.Sc Chemistry','BBA'], naacGrade: 'A' },
  { name: 'Aryabhatta Knowledge University', state: 'Bihar', fees: 25000, courses: ['B.Tech Computer Science','B.Tech Electronics','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Chanakya National Law University', state: 'Bihar', fees: 50000, courses: ['BA LLB','BBA LLB','LLM'], naacGrade: 'A' },
  { name: 'Nalanda Open University', state: 'Bihar', fees: 10000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'Patna Women\'s College', state: 'Bihar', fees: 20000, courses: ['BA English','B.Com','B.Sc Physics','BBA'], naacGrade: 'A' },
  { name: 'St. Xavier\'s College Patna', state: 'Bihar', fees: 30000, courses: ['BA English','B.Com','B.Sc Chemistry','BBA'], naacGrade: 'A' },
  { name: 'Patna Science College', state: 'Bihar', fees: 15000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics','B.Sc Biology'], naacGrade: 'A' },
  
  // CHHATTISGARH - Local & Private Colleges
  { name: 'Pt. Ravishankar Shukla University', state: 'Chhattisgarh', fees: 15000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'Bastar University', state: 'Chhattisgarh', fees: 12000, courses: ['BA English','B.Com','B.Sc Chemistry','BA Political Science'], naacGrade: 'A' },
  { name: 'Sarguja University', state: 'Chhattisgarh', fees: 10000, courses: ['BA History','B.Com','B.Sc Physics','BBA'], naacGrade: 'A' },
  { name: 'Hidayatullah National Law University', state: 'Chhattisgarh', fees: 40000, courses: ['BA LLB','BBA LLB','LLM'], naacGrade: 'A' },
  { name: 'Kalinga University', state: 'Chhattisgarh', fees: 80000, courses: ['B.Tech Computer Science','B.Tech Mechanical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'ITM University Raipur', state: 'Chhattisgarh', fees: 100000, courses: ['B.Tech Computer Science','B.Tech Electronics','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Chhattisgarh Swami Vivekanand Technical University', state: 'Chhattisgarh', fees: 30000, courses: ['B.Tech Computer Science','B.Tech Civil','B.Tech Mechanical'], naacGrade: 'A' },
  { name: 'Indira Gandhi Agricultural University', state: 'Chhattisgarh', fees: 20000, courses: ['B.Sc Agriculture','B.Sc Horticulture','B.Sc Forestry'], naacGrade: 'A' },
  { name: 'Dr. C.V. Raman University', state: 'Chhattisgarh', fees: 60000, courses: ['B.Tech Computer Science','BBA','B.Com','B.Sc Physics'], naacGrade: 'A' },
  { name: 'Amity University Raipur', state: 'Chhattisgarh', fees: 120000, courses: ['B.Tech Computer Science','BBA','B.Com','B.Sc Physics'], naacGrade: 'A' },
  
  // GOA - Local & Private Colleges
  { name: 'Goa University', state: 'Goa', fees: 25000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'BITS Pilani Goa Campus', state: 'Goa', fees: 300000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Mechanical'], naacGrade: 'A' },
  { name: 'Don Bosco College', state: 'Goa', fees: 40000, courses: ['BA English','B.Com','B.Sc Physics','BBA'], naacGrade: 'A' },
  { name: 'St. Xavier\'s College Mapusa', state: 'Goa', fees: 35000, courses: ['BA English','B.Com','B.Sc Chemistry','BBA'], naacGrade: 'A' },
  { name: 'Dhempe College of Arts and Science', state: 'Goa', fees: 30000, courses: ['BA English','B.Com','B.Sc Mathematics','BA History'], naacGrade: 'A' },
  { name: 'Goa College of Engineering', state: 'Goa', fees: 50000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A' },
  { name: 'Goa Medical College', state: 'Goa', fees: 30000, courses: ['MBBS','BDS','B.Pharm'], naacGrade: 'A' },
  { name: 'Goa College of Pharmacy', state: 'Goa', fees: 40000, courses: ['B.Pharm','M.Pharm','D.Pharm'], naacGrade: 'A' },
  { name: 'Goa Institute of Management', state: 'Goa', fees: 150000, courses: ['MBA','PGDM','Executive MBA'], naacGrade: 'A' },
  { name: 'V.M. Salgaocar College of Law', state: 'Goa', fees: 60000, courses: ['BA LLB','LLB','LLM'], naacGrade: 'A' },
  
  // GUJARAT - Local & Private Colleges
  { name: 'Gujarat University', state: 'Gujarat', fees: 20000, courses: ['BA English','B.Com','B.Sc Physics','BA History'], naacGrade: 'A' },
  { name: 'Sardar Patel University', state: 'Gujarat', fees: 18000, courses: ['B.Sc Chemistry','B.Com','BA English','B.Sc Mathematics'], naacGrade: 'A' },
  { name: 'Saurashtra University', state: 'Gujarat', fees: 15000, courses: ['BA History','B.Com','B.Sc Physics','BA Political Science'], naacGrade: 'A' },
  { name: 'Maharaja Sayajirao University of Baroda', state: 'Gujarat', fees: 25000, courses: ['BA English','B.Com','B.Sc Chemistry','BBA'], naacGrade: 'A' },
  { name: 'Dharmsinh Desai University', state: 'Gujarat', fees: 80000, courses: ['B.Tech Computer Science','B.Tech Mechanical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Nirma University', state: 'Gujarat', fees: 150000, courses: ['B.Tech Computer Science','B.Tech Electronics','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Ahmedabad University', state: 'Gujarat', fees: 200000, courses: ['B.Tech Computer Science','BBA','B.Com','B.Sc Physics'], naacGrade: 'A' },
  { name: 'Gujarat Technological University', state: 'Gujarat', fees: 40000, courses: ['B.Tech Computer Science','B.Tech Civil','B.Tech Mechanical'], naacGrade: 'A' },
  { name: 'Gujarat National Law University', state: 'Gujarat', fees: 60000, courses: ['BA LLB','BBA LLB','LLM'], naacGrade: 'A' },
  { name: 'Charotar University of Science and Technology', state: 'Gujarat', fees: 100000, courses: ['B.Tech Computer Science','B.Tech Electronics','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Pandit Deendayal Petroleum University', state: 'Gujarat', fees: 120000, courses: ['B.Tech Computer Science','B.Tech Chemical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'Ganpat University', state: 'Gujarat', fees: 80000, courses: ['B.Tech Computer Science','B.Tech Mechanical','BBA','B.Com'], naacGrade: 'A' },
  { name: 'L.D. College of Engineering', state: 'Gujarat', fees: 30000, courses: ['B.Tech Computer Science','B.Tech Electronics','B.Tech Civil'], naacGrade: 'A' },
  { name: 'Government Engineering College', state: 'Gujarat', fees: 25000, courses: ['B.Tech Computer Science','B.Tech Mechanical','B.Tech Civil'], naacGrade: 'A' },
  { name: 'St. Xavier\'s College Ahmedabad', state: 'Gujarat', fees: 50000, courses: ['BA English','B.Com','B.Sc Physics','BBA'], naacGrade: 'A' },
  
  // Additional NAAC A++ Ranked Colleges
  { name: 'Indian Institute of Management Ahmedabad', state: 'Gujarat', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iima.ac.in' },
  { name: 'Indian Institute of Management Bangalore', state: 'Karnataka', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimb.ac.in' },
  { name: 'Indian Institute of Management Calcutta', state: 'West Bengal', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimcal.ac.in' },
  { name: 'Indian Institute of Management Lucknow', state: 'Uttar Pradesh', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iiml.ac.in' },
  { name: 'Indian Institute of Management Kozhikode', state: 'Kerala', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimk.ac.in' },
  { name: 'Indian Institute of Management Indore', state: 'Madhya Pradesh', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimidr.ac.in' },
  { name: 'All India Institute of Medical Sciences Delhi', state: 'Delhi', fees: 10000, courses: ['MBBS','B.Sc Nursing','BPT'], naacGrade: 'A++', website: 'https://www.aiims.edu' },
  { name: 'Post Graduate Institute of Medical Education and Research', state: 'Chandigarh', fees: 15000, courses: ['MBBS','B.Sc Nursing','BPT'], naacGrade: 'A++', website: 'https://www.pgimer.edu.in' },
  { name: 'Christian Medical College Vellore', state: 'Tamil Nadu', fees: 50000, courses: ['MBBS','B.Sc Nursing','BPT'], naacGrade: 'A++', website: 'https://www.cmch-vellore.edu' },
  { name: 'Armed Forces Medical College', state: 'Maharashtra', fees: 20000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.afmc.nic.in' },
  { name: 'Maulana Azad Medical College', state: 'Delhi', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.mamc.ac.in' },
  { name: 'Lady Hardinge Medical College', state: 'Delhi', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.lhmc-hosp.gov.in' },
  { name: 'Grant Medical College', state: 'Maharashtra', fees: 15000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmcjjh.org' },
  { name: 'Seth GS Medical College', state: 'Maharashtra', fees: 15000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.kem.edu' },
  { name: 'Madras Medical College', state: 'Tamil Nadu', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.mmc.ac.in' },
  { name: 'Osmania Medical College', state: 'Telangana', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.osmaniamedicalcollege.org' },
  { name: 'Bangalore Medical College', state: 'Karnataka', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.bmcri.org' },
  { name: 'Government Medical College Chandigarh', state: 'Chandigarh', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmch.gov.in' },
  { name: 'Government Medical College Patiala', state: 'Punjab', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmcp.ac.in' },
  { name: 'Government Medical College Amritsar', state: 'Punjab', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmca.ac.in' },
  
  // Additional NAAC A+ Ranked Colleges
  { name: 'Indian Institute of Management Udaipur', state: 'Rajasthan', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimu.ac.in' },
  { name: 'Indian Institute of Management Raipur', state: 'Chhattisgarh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimraipur.ac.in' },
  { name: 'Indian Institute of Management Ranchi', state: 'Jharkhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimranchi.ac.in' },
  { name: 'Indian Institute of Management Trichy', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Kashipur', state: 'Uttarakhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimkashipur.ac.in' },
  { name: 'Indian Institute of Management Bodh Gaya', state: 'Bihar', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimbg.ac.in' },
  { name: 'Indian Institute of Management Sambalpur', state: 'Odisha', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimsambalpur.ac.in' },
  { name: 'Indian Institute of Management Sirmaur', state: 'Himachal Pradesh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimsirmaur.ac.in' },
  { name: 'Indian Institute of Management Nagpur', state: 'Maharashtra', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimnagpur.ac.in' },
  { name: 'Indian Institute of Management Amritsar', state: 'Punjab', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimamritsar.ac.in' },
  { name: 'Indian Institute of Management Jammu', state: 'Jammu and Kashmir', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimj.ac.in' },
  { name: 'Indian Institute of Management Visakhapatnam', state: 'Andhra Pradesh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimv.ac.in' },
  { name: 'Indian Institute of Management Shillong', state: 'Meghalaya', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimshillong.ac.in' },
  { name: 'Indian Institute of Management Rohtak', state: 'Haryana', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimrohtak.ac.in' },
  { name: 'Indian Institute of Management Tiruchirappalli', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Udaipur', state: 'Rajasthan', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimu.ac.in' },
  { name: 'Indian Institute of Management Raipur', state: 'Chhattisgarh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimraipur.ac.in' },
  { name: 'Indian Institute of Management Ranchi', state: 'Jharkhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimranchi.ac.in' },
  { name: 'Indian Institute of Management Trichy', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Kashipur', state: 'Uttarakhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimkashipur.ac.in' },
  
  // Additional NAAC A Ranked Colleges
  { name: 'Symbiosis International University', state: 'Maharashtra', fees: 300000, courses: ['MBA','BBA','B.Tech Computer Science','B.Sc'], naacGrade: 'A', website: 'https://www.siu.edu.in' },
  { name: 'Manipal Academy of Higher Education', state: 'Karnataka', fees: 400000, courses: ['MBBS','B.Tech Computer Science','MBA','BBA'], naacGrade: 'A', website: 'https://www.manipal.edu' },
  { name: 'Amity University', state: 'Uttar Pradesh', fees: 200000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.amity.edu' },
  { name: 'Lovely Professional University', state: 'Punjab', fees: 150000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.lpu.in' },
  { name: 'Chandigarh University', state: 'Punjab', fees: 180000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.cuchd.in' },
  { name: 'SRM Institute of Science and Technology', state: 'Tamil Nadu', fees: 250000, courses: ['B.Tech Computer Science','MBBS','MBA','BBA'], naacGrade: 'A', website: 'https://www.srmist.edu.in' },
  { name: 'VIT University', state: 'Tamil Nadu', fees: 200000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.vit.ac.in' },
  { name: 'Bharathiar University', state: 'Tamil Nadu', fees: 50000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.b-u.ac.in' },
  { name: 'Madurai Kamaraj University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.mk university.ac.in' },
  { name: 'Bharathidasan University', state: 'Tamil Nadu', fees: 40000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.bdu.ac.in' },
  { name: 'Annamalai University', state: 'Tamil Nadu', fees: 35000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.annamalaiuniversity.ac.in' },
  { name: 'Alagappa University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.alagappauniversity.ac.in' },
  { name: 'Periyar University', state: 'Tamil Nadu', fees: 25000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.periyaruniversity.ac.in' },
  { name: 'Thiruvalluvar University', state: 'Tamil Nadu', fees: 20000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.tvu.edu.in' },
  { name: 'Mother Teresa Women\'s University', state: 'Tamil Nadu', fees: 15000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.motherteresawomenuniv.ac.in' },
  { name: 'Tamil Nadu Agricultural University', state: 'Tamil Nadu', fees: 40000, courses: ['B.Tech Agriculture','B.Sc Agriculture','MBA','BBA'], naacGrade: 'A', website: 'https://www.tnau.ac.in' },
  { name: 'Tamil Nadu Veterinary and Animal Sciences University', state: 'Tamil Nadu', fees: 50000, courses: ['BVSc','B.Tech Dairy Technology','MBA','BBA'], naacGrade: 'A', website: 'https://www.tanuvas.ac.in' },
  { name: 'Tamil Nadu Dr. Ambedkar Law University', state: 'Tamil Nadu', fees: 60000, courses: ['BA LLB','BBA LLB','LLM'], naacGrade: 'A', website: 'https://www.tndalu.ac.in' },
  { name: 'Tamil Nadu Teachers Education University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Ed','M.Ed','B.P.Ed'], naacGrade: 'A', website: 'https://www.tnteu.ac.in' },
  { name: 'Tamil Nadu Open University', state: 'Tamil Nadu', fees: 20000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.tnou.ac.in' },
  
  // Additional NAAC A++ Ranked Colleges
  { name: 'Indian Institute of Management Ahmedabad', state: 'Gujarat', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iima.ac.in' },
  { name: 'Indian Institute of Management Bangalore', state: 'Karnataka', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimb.ac.in' },
  { name: 'Indian Institute of Management Calcutta', state: 'West Bengal', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimcal.ac.in' },
  { name: 'Indian Institute of Management Lucknow', state: 'Uttar Pradesh', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iiml.ac.in' },
  { name: 'Indian Institute of Management Kozhikode', state: 'Kerala', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimk.ac.in' },
  { name: 'Indian Institute of Management Indore', state: 'Madhya Pradesh', fees: 2000000, courses: ['MBA','PGP','FPM'], naacGrade: 'A++', website: 'https://www.iimidr.ac.in' },
  { name: 'All India Institute of Medical Sciences Delhi', state: 'Delhi', fees: 10000, courses: ['MBBS','B.Sc Nursing','BPT'], naacGrade: 'A++', website: 'https://www.aiims.edu' },
  { name: 'Post Graduate Institute of Medical Education and Research', state: 'Chandigarh', fees: 15000, courses: ['MBBS','B.Sc Nursing','BPT'], naacGrade: 'A++', website: 'https://www.pgimer.edu.in' },
  { name: 'Christian Medical College Vellore', state: 'Tamil Nadu', fees: 50000, courses: ['MBBS','B.Sc Nursing','BPT'], naacGrade: 'A++', website: 'https://www.cmch-vellore.edu' },
  { name: 'Armed Forces Medical College', state: 'Maharashtra', fees: 20000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.afmc.nic.in' },
  { name: 'Maulana Azad Medical College', state: 'Delhi', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.mamc.ac.in' },
  { name: 'Lady Hardinge Medical College', state: 'Delhi', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.lhmc-hosp.gov.in' },
  { name: 'Grant Medical College', state: 'Maharashtra', fees: 15000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmcjjh.org' },
  { name: 'Seth GS Medical College', state: 'Maharashtra', fees: 15000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.kem.edu' },
  { name: 'Madras Medical College', state: 'Tamil Nadu', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.mmc.ac.in' },
  { name: 'Osmania Medical College', state: 'Telangana', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.osmaniamedicalcollege.org' },
  { name: 'Bangalore Medical College', state: 'Karnataka', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.bmcri.org' },
  { name: 'Government Medical College Chandigarh', state: 'Chandigarh', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmch.gov.in' },
  { name: 'Government Medical College Patiala', state: 'Punjab', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmcp.ac.in' },
  { name: 'Government Medical College Amritsar', state: 'Punjab', fees: 10000, courses: ['MBBS','B.Sc Nursing'], naacGrade: 'A++', website: 'https://www.gmca.ac.in' },
  
  // Additional NAAC A+ Ranked Colleges
  { name: 'Indian Institute of Management Udaipur', state: 'Rajasthan', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimu.ac.in' },
  { name: 'Indian Institute of Management Raipur', state: 'Chhattisgarh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimraipur.ac.in' },
  { name: 'Indian Institute of Management Ranchi', state: 'Jharkhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimranchi.ac.in' },
  { name: 'Indian Institute of Management Trichy', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Kashipur', state: 'Uttarakhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimkashipur.ac.in' },
  { name: 'Indian Institute of Management Bodh Gaya', state: 'Bihar', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimbg.ac.in' },
  { name: 'Indian Institute of Management Sambalpur', state: 'Odisha', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimsambalpur.ac.in' },
  { name: 'Indian Institute of Management Sirmaur', state: 'Himachal Pradesh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimsirmaur.ac.in' },
  { name: 'Indian Institute of Management Nagpur', state: 'Maharashtra', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimnagpur.ac.in' },
  { name: 'Indian Institute of Management Amritsar', state: 'Punjab', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimamritsar.ac.in' },
  { name: 'Indian Institute of Management Jammu', state: 'Jammu and Kashmir', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimj.ac.in' },
  { name: 'Indian Institute of Management Visakhapatnam', state: 'Andhra Pradesh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimv.ac.in' },
  { name: 'Indian Institute of Management Shillong', state: 'Meghalaya', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimshillong.ac.in' },
  { name: 'Indian Institute of Management Rohtak', state: 'Haryana', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimrohtak.ac.in' },
  { name: 'Indian Institute of Management Tiruchirappalli', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Udaipur', state: 'Rajasthan', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimu.ac.in' },
  { name: 'Indian Institute of Management Raipur', state: 'Chhattisgarh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimraipur.ac.in' },
  { name: 'Indian Institute of Management Ranchi', state: 'Jharkhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimranchi.ac.in' },
  { name: 'Indian Institute of Management Trichy', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Kashipur', state: 'Uttarakhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimkashipur.ac.in' },
  
  // Additional NAAC A Ranked Colleges
  { name: 'Symbiosis International University', state: 'Maharashtra', fees: 300000, courses: ['MBA','BBA','B.Tech Computer Science','B.Sc'], naacGrade: 'A', website: 'https://www.siu.edu.in' },
  { name: 'Manipal Academy of Higher Education', state: 'Karnataka', fees: 400000, courses: ['MBBS','B.Tech Computer Science','MBA','BBA'], naacGrade: 'A', website: 'https://www.manipal.edu' },
  { name: 'Amity University', state: 'Uttar Pradesh', fees: 200000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.amity.edu' },
  { name: 'Lovely Professional University', state: 'Punjab', fees: 150000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.lpu.in' },
  { name: 'Chandigarh University', state: 'Punjab', fees: 180000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.cuchd.in' },
  { name: 'SRM Institute of Science and Technology', state: 'Tamil Nadu', fees: 250000, courses: ['B.Tech Computer Science','MBBS','MBA','BBA'], naacGrade: 'A', website: 'https://www.srmist.edu.in' },
  { name: 'VIT University', state: 'Tamil Nadu', fees: 200000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.vit.ac.in' },
  { name: 'Bharathiar University', state: 'Tamil Nadu', fees: 50000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.b-u.ac.in' },
  { name: 'Madurai Kamaraj University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.mk university.ac.in' },
  { name: 'Bharathidasan University', state: 'Tamil Nadu', fees: 40000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.bdu.ac.in' },
  { name: 'Annamalai University', state: 'Tamil Nadu', fees: 35000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.annamalaiuniversity.ac.in' },
  { name: 'Alagappa University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.alagappauniversity.ac.in' },
  { name: 'Periyar University', state: 'Tamil Nadu', fees: 25000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.periyaruniversity.ac.in' },
  { name: 'Thiruvalluvar University', state: 'Tamil Nadu', fees: 20000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.tvu.edu.in' },
  { name: 'Mother Teresa Women\'s University', state: 'Tamil Nadu', fees: 15000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.motherteresawomenuniv.ac.in' },
  { name: 'Tamil Nadu Agricultural University', state: 'Tamil Nadu', fees: 40000, courses: ['B.Tech Agriculture','B.Sc Agriculture','MBA','BBA'], naacGrade: 'A', website: 'https://www.tnau.ac.in' },
  { name: 'Tamil Nadu Veterinary and Animal Sciences University', state: 'Tamil Nadu', fees: 50000, courses: ['BVSc','B.Tech Dairy Technology','MBA','BBA'], naacGrade: 'A', website: 'https://www.tanuvas.ac.in' },
  { name: 'Tamil Nadu Dr. Ambedkar Law University', state: 'Tamil Nadu', fees: 60000, courses: ['BA LLB','BBA LLB','LLM'], naacGrade: 'A', website: 'https://www.tndalu.ac.in' },
  { name: 'Tamil Nadu Teachers Education University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Ed','M.Ed','B.P.Ed'], naacGrade: 'A', website: 'https://www.tnteu.ac.in' },
  { name: 'Tamil Nadu Open University', state: 'Tamil Nadu', fees: 20000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.tnou.ac.in' },
  
  // More NAAC A++ Ranked Colleges
  { name: 'Indian Institute of Science Education and Research Pune', state: 'Maharashtra', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserpune.ac.in' },
  { name: 'Indian Institute of Science Education and Research Kolkata', state: 'West Bengal', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserkol.ac.in' },
  { name: 'Indian Institute of Science Education and Research Mohali', state: 'Punjab', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisermohali.ac.in' },
  { name: 'Indian Institute of Science Education and Research Bhopal', state: 'Madhya Pradesh', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserb.ac.in' },
  { name: 'Indian Institute of Science Education and Research Thiruvananthapuram', state: 'Kerala', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisertvm.ac.in' },
  { name: 'Indian Institute of Science Education and Research Tirupati', state: 'Andhra Pradesh', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisertirupati.ac.in' },
  { name: 'Indian Institute of Science Education and Research Berhampur', state: 'Odisha', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserbpr.ac.in' },
  { name: 'Indian Institute of Science Education and Research Nagaland', state: 'Nagaland', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisernagaland.ac.in' },
  { name: 'Indian Institute of Science Education and Research Jammu', state: 'Jammu and Kashmir', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserjammu.ac.in' },
  { name: 'Indian Institute of Science Education and Research Lucknow', state: 'Uttar Pradesh', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserl.ac.in' },
  { name: 'Indian Institute of Science Education and Research Goa', state: 'Goa', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisergoa.ac.in' },
  { name: 'Indian Institute of Science Education and Research Guwahati', state: 'Assam', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserg.ac.in' },
  { name: 'Indian Institute of Science Education and Research Bhopal', state: 'Madhya Pradesh', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserb.ac.in' },
  { name: 'Indian Institute of Science Education and Research Thiruvananthapuram', state: 'Kerala', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisertvm.ac.in' },
  { name: 'Indian Institute of Science Education and Research Tirupati', state: 'Andhra Pradesh', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisertirupati.ac.in' },
  { name: 'Indian Institute of Science Education and Research Berhampur', state: 'Odisha', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserbpr.ac.in' },
  { name: 'Indian Institute of Science Education and Research Nagaland', state: 'Nagaland', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisernagaland.ac.in' },
  { name: 'Indian Institute of Science Education and Research Jammu', state: 'Jammu and Kashmir', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserjammu.ac.in' },
  { name: 'Indian Institute of Science Education and Research Lucknow', state: 'Uttar Pradesh', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iiserl.ac.in' },
  { name: 'Indian Institute of Science Education and Research Goa', state: 'Goa', fees: 200000, courses: ['B.Sc Physics','B.Sc Chemistry','B.Sc Mathematics'], naacGrade: 'A++', website: 'https://www.iisergoa.ac.in' },
  
  // More NAAC A+ Ranked Colleges
  { name: 'Indian Institute of Management Udaipur', state: 'Rajasthan', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimu.ac.in' },
  { name: 'Indian Institute of Management Raipur', state: 'Chhattisgarh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimraipur.ac.in' },
  { name: 'Indian Institute of Management Ranchi', state: 'Jharkhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimranchi.ac.in' },
  { name: 'Indian Institute of Management Trichy', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Kashipur', state: 'Uttarakhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimkashipur.ac.in' },
  { name: 'Indian Institute of Management Bodh Gaya', state: 'Bihar', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimbg.ac.in' },
  { name: 'Indian Institute of Management Sambalpur', state: 'Odisha', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimsambalpur.ac.in' },
  { name: 'Indian Institute of Management Sirmaur', state: 'Himachal Pradesh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimsirmaur.ac.in' },
  { name: 'Indian Institute of Management Nagpur', state: 'Maharashtra', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimnagpur.ac.in' },
  { name: 'Indian Institute of Management Amritsar', state: 'Punjab', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimamritsar.ac.in' },
  { name: 'Indian Institute of Management Jammu', state: 'Jammu and Kashmir', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimj.ac.in' },
  { name: 'Indian Institute of Management Visakhapatnam', state: 'Andhra Pradesh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimv.ac.in' },
  { name: 'Indian Institute of Management Shillong', state: 'Meghalaya', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimshillong.ac.in' },
  { name: 'Indian Institute of Management Rohtak', state: 'Haryana', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimrohtak.ac.in' },
  { name: 'Indian Institute of Management Tiruchirappalli', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Udaipur', state: 'Rajasthan', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimu.ac.in' },
  { name: 'Indian Institute of Management Raipur', state: 'Chhattisgarh', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimraipur.ac.in' },
  { name: 'Indian Institute of Management Ranchi', state: 'Jharkhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimranchi.ac.in' },
  { name: 'Indian Institute of Management Trichy', state: 'Tamil Nadu', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimtrichy.ac.in' },
  { name: 'Indian Institute of Management Kashipur', state: 'Uttarakhand', fees: 1500000, courses: ['MBA','PGP'], naacGrade: 'A+', website: 'https://www.iimkashipur.ac.in' },
  
  // More NAAC A Ranked Colleges
  { name: 'Symbiosis International University', state: 'Maharashtra', fees: 300000, courses: ['MBA','BBA','B.Tech Computer Science','B.Sc'], naacGrade: 'A', website: 'https://www.siu.edu.in' },
  { name: 'Manipal Academy of Higher Education', state: 'Karnataka', fees: 400000, courses: ['MBBS','B.Tech Computer Science','MBA','BBA'], naacGrade: 'A', website: 'https://www.manipal.edu' },
  { name: 'Amity University', state: 'Uttar Pradesh', fees: 200000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.amity.edu' },
  { name: 'Lovely Professional University', state: 'Punjab', fees: 150000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.lpu.in' },
  { name: 'Chandigarh University', state: 'Punjab', fees: 180000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.cuchd.in' },
  { name: 'SRM Institute of Science and Technology', state: 'Tamil Nadu', fees: 250000, courses: ['B.Tech Computer Science','MBBS','MBA','BBA'], naacGrade: 'A', website: 'https://www.srmist.edu.in' },
  { name: 'VIT University', state: 'Tamil Nadu', fees: 200000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.vit.ac.in' },
  { name: 'Bharathiar University', state: 'Tamil Nadu', fees: 50000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.b-u.ac.in' },
  { name: 'Madurai Kamaraj University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.mk university.ac.in' },
  { name: 'Bharathidasan University', state: 'Tamil Nadu', fees: 40000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.bdu.ac.in' },
  { name: 'Annamalai University', state: 'Tamil Nadu', fees: 35000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.annamalaiuniversity.ac.in' },
  { name: 'Alagappa University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.alagappauniversity.ac.in' },
  { name: 'Periyar University', state: 'Tamil Nadu', fees: 25000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.periyaruniversity.ac.in' },
  { name: 'Thiruvalluvar University', state: 'Tamil Nadu', fees: 20000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.tvu.edu.in' },
  { name: 'Mother Teresa Women\'s University', state: 'Tamil Nadu', fees: 15000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.motherteresawomenuniv.ac.in' },
  { name: 'Tamil Nadu Agricultural University', state: 'Tamil Nadu', fees: 40000, courses: ['B.Tech Agriculture','B.Sc Agriculture','MBA','BBA'], naacGrade: 'A', website: 'https://www.tnau.ac.in' },
  { name: 'Tamil Nadu Veterinary and Animal Sciences University', state: 'Tamil Nadu', fees: 50000, courses: ['BVSc','B.Tech Dairy Technology','MBA','BBA'], naacGrade: 'A', website: 'https://www.tanuvas.ac.in' },
  { name: 'Tamil Nadu Dr. Ambedkar Law University', state: 'Tamil Nadu', fees: 60000, courses: ['BA LLB','BBA LLB','LLM'], naacGrade: 'A', website: 'https://www.tndalu.ac.in' },
  { name: 'Tamil Nadu Teachers Education University', state: 'Tamil Nadu', fees: 30000, courses: ['B.Ed','M.Ed','B.P.Ed'], naacGrade: 'A', website: 'https://www.tnteu.ac.in' },
  { name: 'Tamil Nadu Open University', state: 'Tamil Nadu', fees: 20000, courses: ['B.Tech Computer Science','MBA','BBA','B.Com'], naacGrade: 'A', website: 'https://www.tnou.ac.in' }
]
